title: Promobot-education
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
github_home_url: https://github.com/shabu-rov
robox_url: /Robox/
rooky_url: /Rooky/
rrstudio_url: /RRStudio/
test_devices_url: /TestDevices/
V4_url: /V4/
WSL2_url: /WSL2/